RANDOM_STATE = 42

CATEGORICAL_VARIABLES = [
    "attrition",
    "businesstravel",
    "department",
    "education",
    "educationfield",
    "environmentsatisfaction",
    "gender",
    "jobinvolvement",
    "joblevel",
    "jobrole",
    "jobsatisfaction",
    "maritalstatus",
    "overtime",
    "performancerating",
    "relationshipsatisfaction",
    "stockoptionlevel",
    "worklifebalance",
]

VARIABLES_TO_KEEP = [
    "age",
    "attrition",
    "distancefromhome",
    "education",
    "environmentsatisfaction",
    "joblevel",
    "jobsatisfaction",
    "maritalstatussingle",
    "monthlyincome",
    "numcompaniesworked",
    "overtime",
    "percentsalaryhike",
    "relationshipsatisfaction",
    "stockoptionlevel",
    "totalworkingyears",
    "trainingtimeslastyear",
    "worklifebalance",
    "yearsatcompany",
    "yearsincurrentrole",
    "yearssincelastpromotion",
    "yearswithcurrmanager",
]
